### ISSUE TITLE
How to use with GeoPandas?

### ISSUE THREAD

**Issue by metasim** [nmandery/py_geo_interface#4]
I've tried passing a GeoPandas DataFrame several different ways, but each way throws the same exception. This is basically what I'm doing.

```rust
// Rust
...
fn my_func(geo: GeoInterface) -> PyResult<()> {
  ...
  Ok(())
}
```

```python
# Python
gdf: GeoDataFrame = ...

# All of these throw the same exception:
my_func(gdf)
my_func(gdf.geometry)
my_func(gdf['geometry'])
my_func(gdf.__geo_interface__)
```

_Exception_:
```python
ValueError: Unsupported geometry type "FeatureCollection"
```

Any ideas on what I'm doing wrong?

**Comment by nmandery** [comment]
So far this library only supports reading single geometries, as only these have a corresponding representation in `geo-types`. In general the `__geo_interface__` spec supports also Features and FeatureCollections, the geopandas `GeoSeries` you are using here has a `__geo_interface__` representation of a FeatureCollection.

Have a look at the draft in #5, you can use this to pass a `GeoSeries` from python to rust. Its pretty generic as it should work with any iterable of geometries. Activating the `wkb` feature would probably help to gain a bit more performance.

**Comment by metasim** [comment]
@nmandery Thanks for the fantastic help!
